openapi: 3.2.0
info:
  title: Docker Engine Session API
  version: '1.54'
  x-logo:
    url: https://docs.docker.com/assets/images/logo-docker-main.png
  description: The Engine API is an HTTP API served by Docker Engine.
servers:
- url: /v1.54
tags:
- name: Session
paths:
  /session:
    post:
      summary: Initialize interactive session
      description: 'Start a new interactive session with a server. Session allows server to

        call back to the client for advanced capabilities.


        > **Deprecated**: This endpoint is deprecated and will be removed in a future version.

        > Server should support gRPC directly on the listening socket.


        ### Hijacking


        This endpoint hijacks the HTTP connection to HTTP2 transport that allows

        the client to expose gPRC services on that connection.


        For example, the client sends this request to upgrade the connection:


        ```

        POST /session HTTP/1.1

        Upgrade: h2c

        Connection: Upgrade

        ```


        The Docker daemon responds with a `101 UPGRADED` response follow with

        the raw stream:


        ```

        HTTP/1.1 101 UPGRADED

        Connection: Upgrade

        Upgrade: h2c

        ```'
      operationId: Session
      responses:
        101:
          description: no error, hijacking successful
        400:
          description: bad parameter
          content:
            application/vnd.docker.raw-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: server error
          content:
            application/vnd.docker.raw-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
      - Session
components:
  schemas:
    ErrorResponse:
      description: Represents an error.
      type: object
      required:
      - message
      properties:
        message:
          description: The error message.
          type: string
      example:
        message: Something went wrong.
